version: '3'

services: 

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    entrypoint: dockerize -wait tcp://app:3000 -timeout 20s nginx -g 'daemon off;'
    networks: 
      - node-network
    tty: true
    ports:
      - 8080:8080
    depends_on: 
      - app

  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://dbmysql:3306 -timeout 40s node index.js
    networks: 
      - node-network
    tty: true
    depends_on: 
      - dbmysql

  dbmysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: dbmysql
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge      
